apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: ghcr.io/mymirelhub/demoapp:v1.1.3
        name: demoapp
---
apiVersion: v1
kind: Service
metadata:
  name: kargo-demo
spec:
  ports:
  - nodePort: 30082
    port: 3000
    protocol: TCP
    targetPort: 8080
  selector:
    app: kargo-demo
  type: NodePort
---
apiVersion: v1
data:
  env: uat
kind: ConfigMap
metadata:
  name: kargo-demo-content
