apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: your-app
  name: your-app-deployment
  namespace: myapp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - image: mirel1/demoapp:placeholder
        name: your-app-container
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-go-app
  namespace: myapp-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-go-app
  type: ClusterIP
