apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: prod
  template:
    metadata:
      name: kargo
    spec:
      project: default
      source:
        repoURL: https://github.com/MyMirelHub/kargo-demo
        targetRevision: main
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true