name: CI Build, Test, and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Run Go Tests
      working-directory: src
      run: go test -v ./...

  tag:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.bump_version.outputs.new_tag }}  # Store the tag for downstream jobs
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Semantic Version Tag
      id: bump_version
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DEFAULT_BUMP: "patch"
        WITH_V: true
        RELEASE_BRANCHES: "main"
        INITIAL_VERSION: "0.1.0"

  build:
    runs-on: macos-latest 
    needs: [test, tag]  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: mirel1
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          mirel1/demoapp:${{ needs.tag.outputs.version_tag }}