name: CI Build, Test, and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Run Go Tests
      working-directory: src
      run: go test -v ./...


  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Generate semantic version tag using GitHub Tag Bumper Action
    - name: Bump Version and Tag
      id: bump_version
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DEFAULT_BUMP: "patch"      # Default bump type
        WITH_V: true               # Prefix with 'v' (e.g., v1.0.0)
        RELEASE_BRANCHES: "main"   # Only tag commits on the main branch
        INITIAL_VERSION: "0.1.0"   # Starting version if no tags are found
        MAJOR_STRING_TOKEN: "#major"     # Trigger major bump only with "#major" in commit
        PATCH_STRING_TOKEN: "#patch"     # Default patch bump with "#patch" or no token

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        context: .
        push: true
        tags: |
          ghcr.io/mymirelhub/demoapp:${{ steps.bump_version.outputs.new_tag }}