name: CI Build, Test and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Run Go Tests
      working-directory: src
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Git Tag
      id: get_tag
      run: |
        TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
        if [ -z "$TAG" ]; then
          echo "Error: Git tag is required to push an image. Please tag your commit with a semantic version (e.g., v1.0.0)."
          exit 1
        elif [ "$TAG" == "latest" ]; then
          echo "Error: 'latest' tag is not allowed for versioned releases. Please use a semantic version tag."
          exit 1
        fi
        echo "tag=$TAG" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: mirel1
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          mirel1/demoapp:${{ env.tag }}