name: CI Build, Test, and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Run Go Tests
      working-directory: src
      run: go test -v ./...

  build:
    runs-on: macos-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Generate semantic version tag using GitHub Tag Bumper Action
    - name: Bump Version and Tag
      id: bump_version
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DEFAULT_BUMP: "patch"      # Default bump type
        WITH_V: true               # Prefix with 'v' (e.g., v1.0.0)
        RELEASE_BRANCHES: "main"   # Only tag commits on the main branch
        INITIAL_VERSION: "0.1.0"   # Starting version if no tags are found

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: mirel1
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          mirel1/demoapp:${{ steps.bump_version.outputs.new_tag }}